"""Tests for the document builder API."""

from __future__ import annotations

from pathlib import Path

import pytest

from fprime_cpp_codegen import (
    Class,
    CppDocBuilder,
    Function,
    Lines,
    Output,
    Param,
    SVQualifier,
    Type,
    ValidationError,
    Variable,
    as_type,
    line,
    lines,
)
from fprime_cpp_codegen.builder import ClassBuilder
from fprime_cpp_codegen.lines import Line
from fprime_cpp_codegen.writer import HppWriter

from .conftest import assert_compiles


def doc(**kwargs: object) -> CppDocBuilder:
    kwargs.setdefault("description", "test")
    return CppDocBuilder("T", **kwargs)  # type: ignore[arg-type]


class MarkedHpp(HppWriter):
    """An HppWriter subclass that leaves a visible trace, for the writer= tests."""

    def close_include_guard(self) -> list[Line]:
        return [line("// MARKED"), *super().close_include_guard()]


class TestDocumentSetup:
    def test_file_names_follow_the_base(self) -> None:
        d = doc()
        assert d.hpp_name == "T.hpp"
        assert d.cpp_name == "T.cpp"

    def test_extensions_are_configurable(self) -> None:
        d = CppDocBuilder("T", hpp_extension="h", cpp_extension="c")
        assert (d.hpp_name, d.cpp_name) == ("T.h", "T.c")
        assert d.include_guard == "T_H"

    def test_include_guard_is_derived_from_the_namespaces(self) -> None:
        assert CppDocBuilder("MyClass", namespaces=["Fw", "Cfg"]).include_guard == (
            "Fw_Cfg_MyClass_HPP"
        )

    def test_include_guard_can_be_given_outright(self) -> None:
        assert doc(include_guard="CUSTOM_H").include_guard == "CUSTOM_H"

    def test_description_defaults_to_the_file_base(self) -> None:
        assert CppDocBuilder("Widget").description == "Widget"

    def test_a_document_needs_a_name(self) -> None:
        with pytest.raises(ValidationError, match="needs a file name base"):
            CppDocBuilder("")

    def test_tool_name_reaches_the_banner(self) -> None:
        assert "Generated by mytool" in doc(tool_name="mytool").render_hpp()


class TestIncludes:
    def test_quoted_and_system_includes(self) -> None:
        d = doc()
        d.include("A.hpp", "B.hpp")
        d.system_include("cstdio")
        hpp = d.render_hpp()
        assert '#include "A.hpp"' in hpp and '#include "B.hpp"' in hpp
        assert "#include <cstdio>" in hpp

    def test_includes_can_be_source_only(self) -> None:
        d = doc()
        d.include("A.hpp", output=Output.CPP)
        assert '#include "A.hpp"' not in d.render_hpp()
        assert '#include "A.hpp"' in d.render_cpp()

    def test_no_paths_adds_nothing(self) -> None:
        d = doc()
        d.include()
        assert d.build().members == []


class TestAccessSections:
    def test_an_empty_section_leaves_nothing_behind(self) -> None:
        d = doc()
        with d.class_("C") as c:
            with c.public("Nothing here"):
                pass
        hpp = d.render_hpp()
        assert "public:" not in hpp
        assert "Nothing here" not in hpp

    def test_a_section_with_members_keeps_its_label(self) -> None:
        d = doc()
        with d.class_("C") as c:
            with c.public("Interface"):
                c.function("f")
        hpp = d.render_hpp()
        assert "public:" in hpp and "Interface" in hpp

    def test_a_bare_call_takes_effect_immediately(self) -> None:
        d = doc()
        with d.class_("C") as c:
            c.private()
            c.var("U32", "m_x")
        assert "private:" in d.render_hpp()

    def test_all_three_specifiers(self) -> None:
        d = doc()
        with d.class_("C") as c:
            with c.public():
                c.function("a")
            with c.protected():
                c.function("b")
            with c.private():
                c.function("c")
        hpp = d.render_hpp()
        assert "public:" in hpp and "protected:" in hpp and "private:" in hpp

    def test_a_header_only_section_keeps_its_banner_out_of_the_source(self) -> None:
        d = doc()
        with d.class_("C") as c:
            with c.private("Member variables"):
                c.var("U32", "m_x")
        assert "Member variables" in d.render_hpp()
        assert "Member variables" not in d.render_cpp()

    def test_a_section_with_definitions_puts_its_banner_in_both(self) -> None:
        d = doc()
        with d.class_("C") as c:
            with c.public("Public member functions"):
                c.function("f", body="x();")
        assert "Public member functions" in d.render_hpp()
        assert "Public member functions" in d.render_cpp()

    def test_a_standalone_banner_is_unconditional(self) -> None:
        d = doc()
        with d.class_("C") as c:
            c.banner("Always")
            c.var("U32", "m_x")
        assert "Always" in d.render_hpp()
        assert "Always" in d.render_cpp()


class TestCppFileSelection:
    def test_the_block_redirects_definitions(self) -> None:
        d = doc()
        with d.class_("C") as c:
            c.function("here", body="a();")
            with d.cpp_file("Other"):
                c.function("there", body="b();")
            c.function("back", body="c();")
        default, other = d.render_cpp(), d.render_cpp("Other")
        assert "a();" in default and "c();" in default and "b();" not in default
        assert "b();" in other and "a();" not in other

    def test_nested_blocks_restore_the_outer_value(self) -> None:
        d = doc()
        with d.class_("C") as c:
            with d.cpp_file("A"):
                with d.cpp_file("B"):
                    c.function("inner", body="b();")
                c.function("outer", body="a();")
        assert "a();" in d.render_cpp("A") and "b();" not in d.render_cpp("A")
        assert "b();" in d.render_cpp("B") and "a();" not in d.render_cpp("B")

    def test_an_explicit_argument_beats_the_block(self) -> None:
        d = doc()
        with d.class_("C") as c:
            with d.cpp_file("A"):
                c.function("f", body="x();", cpp_file="B")
        assert "x();" in d.render_cpp("B")

    def test_the_block_restores_even_after_an_exception(self) -> None:
        d = doc()
        with pytest.raises(RuntimeError):
            with d.cpp_file("A"):
                raise RuntimeError("boom")
        with d.class_("C") as c:
            c.function("f", body="x();")
        assert "x();" in d.render_cpp()

    def test_files_are_discovered(self) -> None:
        d = doc()
        with d.class_("C") as c:
            with d.cpp_file("Other"):
                c.function("f", body="x();")
        assert set(d.files()) == {"T.hpp", "T.cpp", "Other.cpp"}


class TestIfDirective:
    def test_the_guard_brackets_the_members(self) -> None:
        d = doc()
        with d.class_("C") as c:
            with c.if_directive("#if FW_ENABLE_TEXT_LOGGING"):
                c.function("log")
        hpp = d.render_hpp()
        assert "#if FW_ENABLE_TEXT_LOGGING" in hpp
        assert "#endif" in hpp.split("void log();")[1]

    def test_an_empty_guard_vanishes(self) -> None:
        d = doc()
        with d.class_("C") as c:
            with c.if_directive("#ifdef NOPE"):
                pass
        assert "NOPE" not in d.render_hpp()

    def test_an_exception_discards_what_the_guard_added(self) -> None:
        d = doc()
        with d.class_("C") as c:
            c.function("keep")
            with pytest.raises(RuntimeError):
                with c.if_directive("#ifdef X"):
                    c.function("drop")
                    raise RuntimeError("boom")
        hpp = d.render_hpp()
        assert "keep" in hpp and "drop" not in hpp and "#ifdef X" not in hpp

    def test_the_guard_is_left_aligned(self) -> None:
        d = doc()
        with d.namespace("N") as ns:
            with ns.class_("C") as c:
                with c.if_directive("#ifdef X"):
                    c.function("f")
        assert "\n#ifdef X\n" in d.render_hpp()


class TestNamespaces:
    def test_a_chain_opens_every_level_and_returns_the_innermost(self) -> None:
        d = doc()
        ns = d.namespace("A", "B", "C")
        ns.class_("K")
        hpp = d.render_hpp()
        assert (
            hpp.index("namespace A")
            < hpp.index("namespace B")
            < hpp.index("namespace C")
        )
        assert hpp.index("namespace C") < hpp.index("class K")

    def test_no_names_is_rejected(self) -> None:
        with pytest.raises(ValidationError, match="at least one name"):
            doc().namespace()

    def test_anonymous_namespace(self) -> None:
        d = doc()
        ns = d.anonymous_namespace()
        ns.function("helper", body="x();")
        assert "namespace {" in d.render_cpp()

    def test_class_only_qualifiers_are_rejected_on_a_free_function(self) -> None:
        # These are absent from the signature rather than validated inside it, so a
        # type checker rejects them too instead of only the run.
        d = doc()
        for bad in ("const", "virtual", "pure_virtual", "override", "final"):
            with pytest.raises(TypeError, match=f"unexpected keyword argument '{bad}'"):
                d.function("f", **{bad: True})  # type: ignore[arg-type]


class TestClassMembers:
    def test_extends_accepts_a_string_or_a_sequence(self) -> None:
        d = doc()
        d.class_("A", extends="public Base")
        d.class_("B", extends=["public X", "private Y"])
        hpp = d.render_hpp()
        assert "public Base" in hpp
        assert "public X, private Y" in hpp

    def test_a_class_needs_a_name(self) -> None:
        with pytest.raises(ValidationError, match="a class needs a name"):
            doc().class_("")

    def test_struct(self) -> None:
        d = doc()
        d.struct_("S").var("U32", "x")
        assert "struct S {" in d.render_hpp()

    def test_nested_struct(self) -> None:
        d = doc()
        with d.class_("C") as c:
            c.struct_("Inner").var("U32", "x")
        assert "struct Inner {" in d.render_hpp()

    def test_using_alias(self) -> None:
        d = doc()
        with d.class_("C") as c:
            c.using("Id", "U32", comment="An identifier")
        hpp = d.render_hpp()
        assert "//! An identifier" in hpp and "using Id = U32;" in hpp

    def test_friend(self) -> None:
        d = doc()
        with d.class_("C") as c:
            c.friend("class Tester", comment="For tests")
        assert "friend class Tester;" in d.render_hpp()

    def test_member_splices_ready_made_members(self) -> None:
        d = doc()
        with d.class_("C") as c:
            c.member(Lines([line("// spliced")]), Function("f"))
        hpp = d.render_hpp()
        assert "// spliced" in hpp and "void f();" in hpp

    def test_member_accepts_builders_too(self) -> None:
        d = doc()
        standalone = ClassBuilder("Detached")
        standalone.var("U32", "x")
        d.member(standalone)
        assert "class Detached {" in d.render_hpp()


class TestVariables:
    def test_plain_member(self) -> None:
        d = doc()
        with d.class_("C") as c:
            c.var("U32", "m_x", comment="The x")
        hpp = d.render_hpp()
        assert "//! The x" in hpp and "U32 m_x;" in hpp

    def test_initialiser_and_array(self) -> None:
        d = doc()
        with d.class_("C") as c:
            c.var("U32", "m_x", init="0")
            c.var("U32", "m_data", array="SIZE")
        hpp = d.render_hpp()
        assert "U32 m_x = 0;" in hpp and "U32 m_data[SIZE];" in hpp

    def test_static_member_is_declared_here_and_defined_there(self) -> None:
        d = doc()
        with d.class_("C") as c:
            c.var("U32", "s_count", init="0", static=True)
        assert "static U32 s_count;" in d.render_hpp()
        assert "U32 C::s_count = 0;" in d.render_cpp()

    def test_constexpr_static_is_initialised_in_the_class(self) -> None:
        d = doc()
        with d.class_("C") as c:
            c.var("U32", "MAX", init="10", static=True, constexpr=True)
        assert "static constexpr U32 MAX = 10;" in d.render_hpp()
        assert "MAX" not in d.render_cpp()

    def test_constexpr_static_can_ask_for_an_out_of_line_definition(self) -> None:
        d = doc()
        with d.class_("C") as c:
            c.var(
                "U32",
                "MAX",
                init="10",
                static=True,
                constexpr=True,
                out_of_line_definition=True,
            )
        assert "constexpr U32 C::MAX;" in d.render_cpp()

    def test_namespace_constant_lives_in_the_header(self) -> None:
        d = doc()
        with d.namespace("N") as ns:
            ns.var("U32", "SIZE", init="10", constexpr=True)
        assert "constexpr U32 SIZE = 10;" in d.render_hpp()

    def test_extern_global_is_split_across_the_files(self) -> None:
        d = doc()
        with d.namespace("N") as ns:
            ns.var("U32", "g_count", init="0", extern=True)
        assert "extern U32 g_count;" in d.render_hpp()
        assert "U32 g_count = 0;" in d.render_cpp()

    def test_constexpr_without_an_initialiser_is_rejected(self) -> None:
        d = doc()
        with d.class_("C") as c:
            c.var("U32", "MAX", constexpr=True)
        with pytest.raises(ValidationError, match="needs an initialiser"):
            d.render_hpp()


class TestEnums:
    def test_scoped_enum_with_an_underlying_type(self) -> None:
        d = doc()
        with d.class_("C") as c:
            with c.enum_class("Status", underlying="U8", comment="Codes") as e:
                e.constant("OK", 0, comment="Fine")
                e.constant("BAD", 1)
        hpp = d.render_hpp()
        assert "//! Codes" in hpp
        assert "enum class Status : U8 {" in hpp
        assert "OK = 0, //!< Fine" in hpp
        assert "BAD = 1," in hpp

    def test_auto_numbered_constants(self) -> None:
        d = doc()
        with d.namespace("N") as ns:
            ns.enum("Kind").constants("A", "B")
        hpp = d.render_hpp()
        assert "enum Kind {" in hpp and "A,\n" in hpp and "B,\n" in hpp

    def test_anonymous_enum(self) -> None:
        d = doc()
        with d.class_("C") as c:
            c.enum().constant("SIZE", 10)
        assert "enum {\n" in d.render_hpp()

    def test_expression_values(self) -> None:
        d = doc()
        with d.class_("C") as c:
            c.enum("Mask").constant("BOTH", "A | B")
        assert "BOTH = A | B," in d.render_hpp()

    def test_hex_radix(self) -> None:
        from fprime_cpp_codegen import Radix

        d = doc()
        with d.class_("C") as c:
            c.enum("Ids", radix=Radix.HEX).constant("A", 255)
        assert "A = 0xff," in d.render_hpp()

    def test_an_underlying_type_needs_a_scoped_enum(self) -> None:
        # Unreachable through the scope methods, but EnumBuilder is public.
        from fprime_cpp_codegen import EnumBuilder

        with pytest.raises(ValidationError, match="needs a scoped enum"):
            EnumBuilder("E", underlying="U8")

    def test_a_scoped_enum_needs_a_name(self) -> None:
        from fprime_cpp_codegen import EnumBuilder

        with pytest.raises(ValidationError, match="scoped enum needs a name"):
            EnumBuilder(None, scoped=True)

    def test_a_scoped_enum_exposes_its_qualified_type(self) -> None:
        d = doc()
        with d.class_("C") as c:
            e = c.enum_class("Status")
            e.constant("OK", 0)
            c.function("check", ret=e.type, body="return Status::OK;")
        assert "Status check();" in d.render_hpp()
        assert "C::Status C ::" in d.render_cpp()

    def test_an_anonymous_enum_has_no_type(self) -> None:
        with pytest.raises(ValidationError, match="anonymous enum has no type"):
            _ = doc().class_("C").enum().type


class TestNestedTypeQualification:
    def test_nested_class_type(self) -> None:
        d = doc()
        with d.class_("Outer") as outer:
            inner = outer.class_("Inner")
            inner.var("U32", "x")
            outer.function("make", ret=inner.type, body="return Inner();")
        assert "Inner make();" in d.render_hpp()
        assert "Outer::Inner Outer ::" in d.render_cpp()

    def test_nested_helper_for_types_the_builder_does_not_know(self) -> None:
        d = doc()
        with d.class_("C") as c:
            c.using("Id", "U32")
            c.function("id", ret=c.nested("Id"), const=True, body="return 0;")
        assert "Id id() const;" in d.render_hpp()
        assert "C::Id C ::" in d.render_cpp()

    def test_qualification_is_not_applied_at_namespace_scope(self) -> None:
        # A source file is written inside its namespace, so no qualifier is needed.
        d = doc()
        with d.namespace("N") as ns:
            e = ns.enum_class("Kind")
            assert e.type.cpp_type is None


class TestFunctionQualifiers:
    def test_flags_map_onto_the_qualifier(self) -> None:
        d = doc()
        with d.class_("C") as c:
            for name, kwargs, expected in (
                ("s", {"static": True}, SVQualifier.STATIC),
                ("v", {"virtual": True}, SVQualifier.VIRTUAL),
                ("p", {"pure_virtual": True}, SVQualifier.PURE_VIRTUAL),
                ("o", {"override": True}, SVQualifier.OVERRIDE),
                ("f", {"final": True}, SVQualifier.FINAL),
            ):
                assert c.function(name, **kwargs).build().sv is expected

    def test_virtual_and_pure_virtual_together_is_allowed_as_redundant(self) -> None:
        fn = doc().class_("C").function("f", virtual=True, pure_virtual=True)
        assert fn.build().sv is SVQualifier.PURE_VIRTUAL

    def test_static_and_virtual_together_is_rejected(self) -> None:
        with pytest.raises(ValidationError, match="cannot be static and virtual"):
            doc().class_("C").function("f", static=True, virtual=True)

    def test_pure_virtual_and_static_together_is_rejected(self) -> None:
        with pytest.raises(ValidationError, match="pure virtual function cannot also"):
            doc().class_("C").function("f", pure_virtual=True, static=True)

    def test_a_function_needs_a_name(self) -> None:
        with pytest.raises(ValidationError, match="a function needs a name"):
            doc().class_("C").function("")


class TestParameterCoercion:
    def test_tuple_forms(self) -> None:
        fn = (
            doc()
            .class_("C")
            .function(
                "f",
                params=[
                    ("U32", "a"),
                    ("U32", "b", "the b"),
                    ("U32", "c", "the c", "0"),
                    Param(Type("U32"), "d"),
                ],
            )
        )
        params = fn.build().params
        assert [p.name for p in params] == ["a", "b", "c", "d"]
        assert params[1].comment == "the b"
        assert params[2].default == "0"

    def test_a_malformed_tuple_is_rejected(self) -> None:
        with pytest.raises(ValidationError, match="should be a Param"):
            doc().class_("C").function("f", params=[("U32",)])

    def test_param_and_params_methods(self) -> None:
        fn = doc().class_("C").function("f")
        fn.param("U32", "a", comment="the a").params(("U32", "b"))
        assert [p.name for p in fn.build().params] == ["a", "b"]


class TestTypeCoercion:
    def test_string_type(self) -> None:
        assert as_type("U32") == Type("U32")

    def test_pair_supplies_both_spellings(self) -> None:
        assert as_type(("Status", "C::Status")) == Type("Status", "C::Status")

    def test_type_passes_through(self) -> None:
        t = Type("A", "B")
        assert as_type(t) is t

    def test_ret_accepts_all_three(self) -> None:
        c = doc().class_("C")
        assert c.function("a", ret="U32").build().ret_type == Type("U32")
        assert c.function("b", ret=("S", "C::S")).build().ret_type == Type("S", "C::S")
        assert c.function("c", ret=Type("X")).build().ret_type == Type("X")


class TestBodyForms:
    def test_a_string_body(self) -> None:
        d = doc()
        with d.class_("C") as c:
            c.function("f", body="a();\n|b();")
        cpp = d.render_cpp()
        assert "a();" in cpp and "b();" in cpp

    def test_a_line_list_body(self) -> None:
        d = doc()
        with d.class_("C") as c:
            c.function("f", body=[line("a();")])
        assert "a();" in d.render_cpp()

    def test_the_body_can_be_filled_in_after_creation(self) -> None:
        d = doc()
        with d.class_("C") as c:
            fn = c.function("f")
            c.function("g", body="g();")
        fn.body.line("f();")
        cpp = d.render_cpp()
        # Order follows creation, not the order bodies were filled in.
        assert cpp.index("f();") < cpp.index("g();")


class TestBuildContract:
    def test_build_is_idempotent(self) -> None:
        d = doc()
        with d.class_("C") as c:
            c.function("f", body="a();")
        assert d.build() == d.build()
        assert d.render_hpp() == d.render_hpp()

    def test_a_document_can_be_extended_after_being_built(self) -> None:
        d = doc()
        d.class_("A")
        first = d.render_hpp()
        d.class_("B")
        second = d.render_hpp()
        assert "class B" not in first and "class B" in second

    def test_builders_resolve_to_ir_nodes(self) -> None:
        d = doc()
        with d.class_("C") as c:
            c.function("f")
        outer = d.build().members[0]
        assert isinstance(outer, Class)
        assert isinstance(outer.members[0], Function)

    def test_var_builds_a_variable_node(self) -> None:
        d = doc()
        with d.class_("C") as c:
            c.var("U32", "x")
        built = d.build().members[0]
        assert isinstance(built, Class)
        assert isinstance(built.members[0], Variable)


class TestWriting:
    def test_write_creates_every_file(self, tmp_path: object) -> None:
        from pathlib import Path

        assert isinstance(tmp_path, Path)
        d = doc()
        with d.class_("C") as c:
            c.function("f", body="a();")
            with d.cpp_file("Other"):
                c.function("g", body="b();")
        result = d.write(tmp_path)
        assert sorted(p.name for p in result.written) == ["Other.cpp", "T.cpp", "T.hpp"]


def test_a_realistic_document_compiles() -> None:
    d = CppDocBuilder(
        "Ring",
        description="a fixed-capacity ring buffer",
        namespaces=["Demo"],
        tool_name="ring-gen",
    )
    d.lines("using U32 = unsigned int;")
    d.include("Ring.hpp", output=Output.CPP)

    with d.namespace("Demo") as ns:
        with ns.class_("Ring", comment="A ring buffer of fixed capacity") as c:
            with c.public("Types"):
                status = c.enum_class(
                    "Status", underlying="U32", comment="Result codes"
                )
                status.constant("OK", 0, comment="Accepted")
                status.constant("FULL", 1, comment="At capacity")

            with c.public("Constructors and destructors"):
                ctor = c.constructor(explicit=True, comment="Build an empty ring")
                ctor.param("U32", "capacity", comment="The capacity")
                ctor.init("m_head(0)", "m_size(0)", "m_capacity(capacity)")
                c.constructor(params=[("const Ring&", "other")], deleted=True)
                c.destructor(defaulted=True)

            with c.public("Public member functions"):
                push = c.function("push", ret=status.type, comment="Append an item")
                push.param("U32", "item", comment="The item")
                with push.body as b:
                    with b.if_("m_size == m_capacity"):
                        b.line("return Status::FULL;")
                    b.line("m_data[(m_head + m_size) % CAPACITY] = item;")
                    b.line("m_size++;")
                    b.line("return Status::OK;")

                c.function(
                    "size", ret="U32", const=True, inline=True, body="return m_size;"
                )

                describe = c.function("describe", const=True)
                with describe.body as b:
                    with b.switch("m_size") as sw:
                        with sw.case("0"):
                            b.comment("nothing to say")
                        with sw.default():
                            b.line("(void) m_size;")

            with c.private("Member variables"):
                c.var("U32", "CAPACITY", init="64", static=True, constexpr=True)
                c.var("U32", "m_data", array="CAPACITY")
                c.var("U32", "m_head")
                c.var("U32", "m_size")
                c.var("U32", "m_capacity", const=True)

    assert_compiles(d.files())


class TestAttributes:
    """The builder side of declaration attributes."""

    VISIBLE = '__attribute__((visibility("default")))'

    def test_a_single_string_is_one_attribute_not_a_sequence_of_letters(self) -> None:
        d = doc()
        d.class_("C", attributes=self.VISIBLE)
        assert f"class {self.VISIBLE} C {{" in d.render_hpp()

    def test_a_sequence_is_taken_in_order(self) -> None:
        d = doc()
        d.class_("C", attributes=["[[a]]", "[[b]]"])
        assert "class [[a]] [[b]] C {" in d.render_hpp()

    def test_a_struct_takes_them(self) -> None:
        d = doc()
        d.struct_("S", attributes="[[a]]")
        assert "struct [[a]] S {" in d.render_hpp()

    def test_a_nested_class_takes_them(self) -> None:
        d = doc()
        with d.class_("Outer") as cls:
            cls.class_("Inner", attributes="[[a]]")
        assert "class [[a]] Inner {" in d.render_hpp()

    def test_a_free_function_takes_them(self) -> None:
        d = doc()
        d.function("f", attributes="[[nodiscard]]", ret="U32", body="return 0;")
        assert "[[nodiscard]] U32 f();" in d.render_hpp()

    def test_a_member_function_takes_them(self) -> None:
        d = doc()
        with d.class_("C") as cls:
            cls.function("f", attributes="[[nodiscard]]", ret="U32", body="return 0;")
        assert "[[nodiscard]] U32 f();" in d.render_hpp()

    def test_an_exported_class_keeps_its_qualified_definitions_clean(self) -> None:
        # The whole point of a separate field: the name stays usable everywhere.
        d = doc()
        d.include("T.hpp", output=Output.CPP)
        with d.class_("C", attributes=self.VISIBLE) as cls:
            with cls.public():
                cls.constructor(body="")
                cls.destructor(body="")
                cls.function("f", ret="int", body="return 0;")
        cpp = d.render_cpp()
        assert self.VISIBLE not in cpp
        assert_compiles(d.files())


class TestDocumentWriters:
    """``CppDocBuilder`` takes writers document-wide, like it takes a formatter."""

    def test_a_document_wide_writer_reaches_render(self) -> None:
        d = doc(hpp_writer=MarkedHpp())
        d.class_("C")
        assert "// MARKED" in d.render_hpp()

    def test_a_document_wide_writer_reaches_files(self) -> None:
        d = doc(hpp_writer=MarkedHpp())
        d.class_("C")
        assert "// MARKED" in d.files()["T.hpp"]

    def test_a_document_wide_writer_reaches_write(self, tmp_path: Path) -> None:
        d = doc(hpp_writer=MarkedHpp())
        d.class_("C")
        d.write(tmp_path)
        assert "// MARKED" in (tmp_path / "T.hpp").read_text()

    def test_a_call_can_override_the_document_writer(self) -> None:
        d = doc()
        d.class_("C")
        assert "// MARKED" in d.render_hpp(writer=MarkedHpp())

    def test_a_writer_subclass_keeps_the_skip_unchanged_behaviour(
        self, tmp_path: Path
    ) -> None:
        # The point of threading writers through: none of write()'s work is lost.
        d = doc(hpp_writer=MarkedHpp())
        d.class_("C")
        d.write(tmp_path)
        result = d.write(tmp_path)
        assert result.written == []
        assert len(result.unchanged) == 2


class TestMarginEscapes:
    """Text a generator derives from its input must not lose a leading marker."""

    def test_scope_lines_strips_by_default(self) -> None:
        d = doc()
        d.lines("|using T = int;")
        assert "using T = int;" in d.render_hpp()

    def test_scope_lines_can_turn_stripping_off(self) -> None:
        d = doc()
        d.lines('|static const char* S = "|a";', margin=None)
        assert '|static const char* S = "|a";' in d.render_hpp()

    def test_a_comment_from_a_string_is_stripped(self) -> None:
        d = doc()
        d.class_("C", comment="|annotated")
        assert "//! annotated" in d.render_hpp()

    def test_a_comment_from_lines_is_not(self) -> None:
        # What a generator does with an FPP annotation it must not truncate.
        d = doc()
        d.class_("C", comment=lines("|annotated", margin=None))
        assert "//! |annotated" in d.render_hpp()

    def test_a_multi_line_derived_comment_keeps_every_marker(self) -> None:
        d = doc()
        with d.class_("C") as cls:
            cls.function("f", comment=lines("|a\n|b", margin=None), body="x();")
        hpp = d.render_hpp()
        assert "//! |a" in hpp and "//! |b" in hpp

    def test_a_derived_param_comment_keeps_its_marker(self) -> None:
        d = doc()
        with d.class_("C") as cls:
            fn = cls.function("f", body="x();")
            fn.param("U32", "x", comment=lines("|the x", margin=None))
        assert "//!< |the x" in d.render_hpp()

    def test_a_derived_enum_comment_keeps_its_marker(self) -> None:
        d = doc()
        e = d.enum_class("E", underlying="U8")
        e.constant("A", 0, comment=lines("|first", margin=None))
        assert "//!< |first" in d.render_hpp()

    def test_a_derived_variable_comment_keeps_its_marker(self) -> None:
        d = doc()
        d.var("U32", "x", init="0", constexpr=True, comment=[line("|note")])
        assert "//! |note" in d.render_hpp()

    def test_content_starting_with_a_hash_keeps_its_indentation(self) -> None:
        # A docstring being bound to C++, indented inside a raw string literal.
        d = doc()
        with d.class_("C") as cls:
            fn = cls.function("f", body='const char* s = R"(')
            fn.body.line("# Heading")
            fn.body.line(')";')
        assert "  # Heading" in d.render_cpp()


class TestValidation:
    """The checks that stop the builder emitting C++ that would not compile."""

    def test_a_default_argument_must_be_trailing(self) -> None:
        d = doc()
        with d.class_("C") as c:
            c.function("f", params=[("U32", "a", "", "0"), ("U32", "b")])
        with pytest.raises(ValidationError, match="default arguments to be trailing"):
            d.render_hpp()

    def test_extern_and_static_contradict_each_other(self) -> None:
        d = doc()
        d.var("U32", "x", init="0", static=True, extern=True)
        with pytest.raises(ValidationError, match="both extern and static"):
            d.render_hpp()

    def test_extern_does_not_apply_to_a_data_member(self) -> None:
        d = doc()
        with d.class_("C") as c:
            c.var("U32", "m_x", extern=True)
        with pytest.raises(ValidationError, match="use static instead"):
            d.render_hpp()

    def test_mutable_only_applies_to_a_data_member(self) -> None:
        d = doc()
        d.var("U32", "x", mutable=True)
        with pytest.raises(ValidationError, match="only means something for a class"):
            d.render_hpp()

    def test_static_and_mutable_contradict_each_other(self) -> None:
        d = doc()
        with d.class_("C") as c:
            c.var("U32", "m_x", static=True, mutable=True)
        with pytest.raises(ValidationError, match="both static and mutable"):
            d.render_hpp()

    def test_an_empty_string_in_a_tuple_means_not_given(self) -> None:
        # Lets the tuple form supply a default without inventing a comment.
        d = doc()
        with d.class_("C") as c:
            c.function("f", params=[("U32", "a", "", "0")])
        assert "void f(U32 a = 0);" in d.render_hpp()

    def test_deleted_with_a_body_is_rejected(self) -> None:
        d = doc()
        with d.class_("C") as c:
            c.destructor(deleted=True, body="x();")
        with pytest.raises(ValidationError, match="cannot also have a body"):
            d.render_hpp()

    def test_a_constructor_cannot_be_added_at_namespace_scope(self) -> None:
        # Unreachable through the scope methods; this covers hand-assembled IR.
        from fprime_cpp_codegen import Constructor, CppCodegenError

        d = doc()
        d.member(Constructor())
        with pytest.raises(CppCodegenError, match="only appear inside a class"):
            d.render_hpp()


class TestDecorationPlacementAcrossFiles:
    """A banner or guard must land where the members it decorates actually went.

    A single decoration pinned to no file lands in the default source file, which
    is wrong twice over when the members went elsewhere: it heads nothing where it
    appears, and is missing where it is needed.  For a guard that is worse than
    untidy -- the definition compiles unguarded.
    """

    def test_a_banner_follows_its_members_to_a_supplemental_file(self) -> None:
        d = doc()
        with d.class_("C") as c:
            with c.public("Helpers"):
                with d.cpp_file("Other"):
                    c.function("f", body="a();")
        assert "Helpers" not in d.render_cpp()
        other = d.render_cpp("Other")
        assert "Helpers" in other
        assert other.index("Helpers") < other.index("a();")

    def test_a_banner_prefers_the_default_file_when_it_has_any_members(self) -> None:
        # One copy suffices for decoration.
        d = doc()
        with d.class_("C") as c:
            with c.public("Helpers"):
                c.function("here", body="a();")
                with d.cpp_file("Other"):
                    c.function("there", body="b();")
        assert "Helpers" in d.render_cpp()
        assert "Helpers" not in d.render_cpp("Other")

    def test_a_guard_follows_its_members_to_a_supplemental_file(self) -> None:
        d = doc()
        with d.class_("C") as c:
            with c.if_directive("#ifdef BUILD_UT"):
                with d.cpp_file("Other"):
                    c.function("f", body="a();")
        assert "BUILD_UT" not in d.render_cpp()
        other = d.render_cpp("Other")
        assert other.index("#ifdef BUILD_UT") < other.index("a();")
        assert other.index("a();") < other.index("#endif")

    def test_a_guard_is_repeated_into_every_file_it_needs_to_cover(self) -> None:
        d = doc()
        with d.class_("C") as c:
            with c.if_directive("#ifdef BUILD_UT"):
                c.function("here", body="a();")
                with d.cpp_file("Other"):
                    c.function("there", body="b();")
        for target, body in ((None, "a();"), ("Other", "b();")):
            out = d.render_cpp(target)
            assert out.count("#ifdef BUILD_UT") == 1
            assert out.count("#endif") == 1
            assert out.index("#ifdef BUILD_UT") < out.index(body) < out.index("#endif")

    def test_a_header_only_guard_stays_out_of_the_sources(self) -> None:
        d = doc()
        with d.class_("C") as c:
            with c.if_directive("#ifdef BUILD_UT"):
                c.function("f", pure_virtual=True)
        assert "#ifdef BUILD_UT" in d.render_hpp()
        assert "BUILD_UT" not in d.render_cpp()

    def test_a_guard_covers_a_definition_added_after_the_block_closed(self) -> None:
        # Placement is resolved at build time.
        d = doc()
        with d.class_("C") as c:
            with c.if_directive("#ifdef BUILD_UT"):
                fn = c.function("f")
        fn.body.line("a();")
        cpp = d.render_cpp()
        assert cpp.index("#ifdef BUILD_UT") < cpp.index("a();") < cpp.index("#endif")
